Repository g4edge/pyg4ometry, pull requests merged in 2023-08, with the labels that each got.

#100 visualisation : (enhancement) Cutter plotting
  docs/source/manual/viewing.rst
  src/pyg4ometry/cli.py
  src/pyg4ometry/pyoce/__init__.py
  src/pyg4ometry/visualisation/Plot.py
  src/pyg4ometry/visualisation/VtkExporter.py
  src/pyg4ometry/visualisation/VtkViewer.py
  src/pyg4ometry/visualisation/VtkViewerNew.py
  src/pyg4ometry/visualisation/__init__.py
Labels: documentation, enhancement

#88 pyoce : (feature) Code to extract 2d (uv) surfaces and curves
  src/pyg4ometry/pyoce/BRep.cxx
  src/pyg4ometry/pyoce/Geom.cxx
  src/pyg4ometry/pyoce/TopoDS.cxx
  tests/pyoce/test_pyoce.py
Labels: enhancement

#93 pycgal : (test) Mesh comparision tests
  src/pyg4ometry/misc/TestUtils.py
  src/pyg4ometry/pycgal/core.py
  tests/geant4/T001_Box.py
Labels: test

#95 pycgal : (feature) Half space upgrades
  src/pyg4ometry/pycgal/CGAL.cxx
  src/pyg4ometry/pycgal/HalfPlane.py
  src/pyg4ometry/pycgal/Nef_polyhedron_3.cxx
  src/pyg4ometry/pycgal/Plane_3.cxx
  src/pyg4ometry/pycgal/Point_3.cxx
  src/pyg4ometry/pycgal/Polygon_mesh_processing.cxx
  src/pyg4ometry/pycgal/Polyhedron_3.cxx
  src/pyg4ometry/pycgal/Surface_mesh.cxx
  src/pyg4ometry/pycgal/Vector_3.cxx
  src/pyg4ometry/pycgal/__init__.py
Labels: enhancement
